python src/train.py --output_dir "./src/models/checkpoints/training_session"           \
                   --content_datapath "./src/data/dummy/content"  \
                   --style_datapath "./src/data/dummy/style"      \
                   --batch_size 1                                \
                   --max_style_train_samples 5                   \
                   --max_content_train_samples 10                \
                   --max_eval_samples 5                          \
                   --seed 42                                     \
                   --num_train_epochs 10                         \
                   --learning_rate 5e-5                          \
                   --alpha 1                                     \
                   --beta 1                                      \
                   --gamma 1                                     \
                   --delta 1                                     \
                   --width 64                                    \
                   --height 64                                   \
                   --crop_width 32                               \
                   --crop_height 32                              \
                   --content_layers_idx 8 11 13                  \
                   --style_layers_idx 1 3 6 8                    \
                   --transformer_size 16