name: Test train

on:
  push:
    paths:
      - '!README.md'
      - 'src/**.py'
      - 'src/models/**.py'
      - 'src/scripts/**.sh'
      - 'utils/**.py'
      - '.github/workflows/**.yml'
      - '**.py'
      - 'requirements.txt'
    branches:
      - 'main'
      - 'dev'
      - '!feat/**'
  pull_request:
    type: [opened, reopened, synchronize]
    paths:
      - '!README.md'
      - 'src/**.py'
      - 'src/models/**.py'
      - 'src/scripts/**.sh'
      - 'utils/**.py'
      - '.github/workflows/**.yml'
      - '**.py'
      - 'requirements.txt'
    branches:
      - 'main'
      - 'dev'
      - '!feat/**'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install wandb
          pip install matplotlib

      - name: Cache pip dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: List files
        run: ls

# ubuntu
#      - name: Running training script
#        run: ./scripts/train_test

      - name: Running training script
        run: bash src/scripts/train_test.sh